server:
  port: 8080
spring:
  application:
    name: matrix-gateway
  cloud:
    gateway:
      routes:
        - id: test
          uri: https://matrix.seu.edu.cn
          predicates:
            - Path=/api/**




cas:
  casServiceUrl: https://auth.seu.edu.cn/cas
  casServerLoginUrl: https://auth.seu.edu.cn/dist/#/dist/main/login
  serverName: http://127.0.0.1:8080
  whiteUrl: /api/cas/call-back|/api/cas/login|/api/swagger.*|/api/webjar.*|/api/v2.*

